### ISSUE TITLE
Targeting all .ts files in a directory without manually specifying them all

### ISSUE THREAD

**Issue by flamendless** [hazzard993/love-typescript-definitions#1]
Hi, i want to try typescript for love development.
```
"files": [
        "main.ts"               // Can be given more .ts files as your project grows
    ],
```
so all of my .ts file should be added to `"files":` ? (I think it's not convenient)

**Comment by hazzard993** [comment]
Thanks for the first question! 🎉 

I'll update the documents to use `include` instead of `files`. For `files` you can only specify specific files but for `include` you can use wildcards to include multiple TypeScript files.

In your `tsconfig.json` file your `include` parameter should look somewhat like this:
```js
{
    ...
    "include": [
        "*.ts",     // any file ending in ts within the current directory (such as main.ts) is targeted for transpilation
                    // d.ts files are not transpiled
        "../love-typescript-definitions/include/*.d.ts"
    ]
}
```

**Comment by flamendless** [comment]
Thanks!

Suggestion: an example source code of a simple love game made with typescripttolua (and your repo) would be good :)
