### ISSUE TITLE
Property 'push' does not exist on type 'number[]'.

### ISSUE THREAD

**Issue by notexplosive** [hazzard993/love-typescript-definitions#2]
I've been playing around with this and I really like it so far! However I ran into a weird problem trying to work with arrays.

```
let arr:number[] = []
arr.push(5)
```

In the playground this yields `__TS__ArrayPush(arr, 5);` but instead I get the compile-time (transpile-time?) error:  `Property 'push' does not exist on type 'number[]'.`

**Comment by hazzard993** [comment]
Thanks for the post! 😄 

Ah yes, this is because my definition of an array from these definitions is just

```ts
interface Array<T> {
    length: number;
}
```

So `push` doesn't exist on any `[]` type.

TypescriptToLua does some special things once you add a dot to array. See [this function](https://github.com/Perryvw/TypescriptToLua/blob/a61f8412dc490c3cec650b886eb1bbce3be8224a/src/Transpiler.ts#L1313-L1359)

I'll add some more properties into `Array` so they can be used. These will include `push`
